INSERT INTO `geo-service`.Country(id, country_id, phone_code, deleted) VALUES (1, 'it', '39', 0);
INSERT INTO `geo-service`.Country(id, country_id, phone_code, deleted) VALUES (2, 'es', '49', 0);
INSERT INTO `geo-service`.Country(id, country_id, phone_code, deleted) VALUES (3, 'de', '34', 0);

INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (1, 'it', 'italia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (2, 'en', 'italy');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (3, 'it', 'spagna');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (4, 'en', 'spain');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (5, 'it', 'germania');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (6, 'en', 'germany');

INSERT INTO `geo-service`.country_localization(country_id, local_id) VALUES (1, 1);
INSERT INTO `geo-service`.country_localization(country_id, local_id) VALUES (1, 2);
INSERT INTO `geo-service`.country_localization(country_id, local_id) VALUES (2, 3);
INSERT INTO `geo-service`.country_localization(country_id, local_id) VALUES (2, 4);
INSERT INTO `geo-service`.country_localization(country_id, local_id) VALUES (3, 5);
INSERT INTO `geo-service`.country_localization(country_id, local_id) VALUES (3, 6);

INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (100, 'it-abr', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (101, 'it-bas', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (102, 'it-cal', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (103, 'it-cam', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (104, 'it-emr', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (105, 'it-fvg', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (106, 'it-laz', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (107, 'it-lig', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (108, 'it-lom', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (109, 'it-mar', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (110, 'it-mol', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (111, 'it-pie', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (112, 'it-pat', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (113, 'it-pab', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (114, 'it-pug', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (115, 'it-sar', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (116, 'it-sic', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (117, 'it-tos', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (118, 'it-tre', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (119, 'it-umb', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (120, 'it-val', 1, 0);
INSERT INTO `geo-service`.Region(id, region_id, country_id, deleted) VALUES (121, 'it-ven', 1, 0);


INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (500, 'it', 'abruzzo');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (501, 'it', 'basilicata');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (502, 'it', 'calabria');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (503, 'it', 'campania');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (504, 'it', 'emilia romagna');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (505, 'it', 'friuli venezia giulia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (506, 'it', 'lazio');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (507, 'it', 'liguria');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (508, 'it', 'lombardia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (509, 'it', 'marche');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (510, 'it', 'molise');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (511, 'it', 'piemonte');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (512, 'it', 'provincia autonoma di trento');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (513, 'it', 'provincia autonoma di bolzano');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (514, 'it', 'puglia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (515, 'it', 'sardegna');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (516, 'it', 'sicilia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (517, 'it', 'toscana');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (518, 'it', 'trentino alto adige');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (519, 'it', 'umbria');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (520, 'it', 'valle d''aosta');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (521, 'it', 'veneto');

INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (600, 'en', 'abruzzo');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (601, 'en', 'basilicata');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (602, 'en', 'calabria');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (603, 'en', 'campania');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (604, 'en', 'emilia romagna');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (605, 'en', 'friuli venezia giulia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (606, 'en', 'lazio');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (607, 'en', 'liguria');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (608, 'en', 'lombardy');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (609, 'en', 'marche');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (610, 'en', 'molise');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (611, 'en', 'piedmont');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (612, 'en', 'autonomous province of trento');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (613, 'en', 'autonomous province of bolzano');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (614, 'en', 'apulia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (615, 'en', 'sardinia');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (616, 'en', 'sicily');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (617, 'en', 'tuscany');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (618, 'en', 'trentino south tyrol');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (619, 'en', 'umbria');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (620, 'en', 'aosta valley');
INSERT INTO `geo-service`.localized_data(id, language_id, data) VALUES (621, 'en', 'veneto');

INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (100, 500);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (101, 501);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (102, 502);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (103, 503);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (104, 504);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (105, 505);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (106, 506);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (107, 507);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (108, 508);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (109, 509);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (110, 510);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (111, 511);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (112, 512);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (113, 513);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (114, 514);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (115, 515);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (116, 516);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (117, 517);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (118, 518);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (119, 519);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (120, 520);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (121, 521);

INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (100, 600);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (101, 601);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (102, 602);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (103, 603);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (104, 604);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (105, 605);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (106, 606);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (107, 607);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (108, 608);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (109, 609);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (110, 610);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (111, 611);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (112, 612);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (113, 613);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (114, 614);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (115, 615);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (116, 616);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (117, 617);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (118, 618);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (119, 619);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (120, 620);
INSERT INTO `geo-service`.region_localization(region_id, local_id) VALUES (121, 621);
